Dependancy/Nodejs version updates
fardog/node-xkcd-password pull request #10
Opened 2016-12-20 22:08 UTC by cabbiepete

Updated to work with latest versions of dependancies, random-lib, async etc. and also nodes 4.x and above.

2016-12-20 22:35 UTC, fardog requested changes
thanks tons for this PR! i'd been meaning to get around to this!

just one nit to correct please; after that's done I'll merge this and release as v2.0.0.

thank you!

2016-12-20 22:35 UTC, fardog commented on package.json
> +  "version": "2.0.0",
please revert this line; i prefer to bump versions with `npm version major` on the CLI for the auto git tagging and etc.

2016-12-21 21:12 UTC, cabbiepete commented on package.json
> +  "version": "2.0.0",
Ok sure that's exactly what I did but I guess the tag does not come through with the pull request.

2016-12-21 21:19 UTC, cabbiepete reviewed
Done

2016-12-21 21:47 UTC, fardog approved these changes

2016-12-21 21:48 UTC, merged

2016-12-21 21:56 UTC, cabbiepete commented
Thanks for the quick response.

2016-12-21 23:01 UTC, fardog commented
no problem; thank you for the pr! version 2.0.0 has been published.